# Evaluation Parameters
red_agent: rl_red_campaign.yaml
blue_agent: dynamic_blue_agent.yaml
environment: CyberwheelEmulator
valid_targets: servers
train_red: false
train_blue: true
red_model: EmulatorRed_IntegrationConfig
blue_model: EmulatorBlue_IntegrationConfig
campaign: true
seed: 1

checkpoint: agent
download_model: false
blue_run: y33xqd7d
red_run: dtelbqdi
wandb_project_name: Cyberwheel # required if download_model is true
wandb_entity: oeschsec # required if download_model is true

experiment: EmulatorTestIntegrationConfig
visualize: false
graph_name: EmulatorTestIntegrationConfig
network_config: integration_config.yaml
decoy_config: decoy_hosts.yaml
host_config: host_defs_services.yaml
detector_config: detector_handler.yaml
min_decoys: 2
max_decoys: 3
reward_scaling: 10.0
reward_function: RLRedReward
num_steps: 100
num_episodes: 10
