# Evaluation Parameters
red_agent: targeted_encryption_campaign.yaml
blue_agent: dynamic_blue_agent.yaml
environment: CyberwheelEmulator
valid_targets: all
train_red: false
train_blue: true
campaign: true
seed: 1

checkpoint: agent
download_model: true
run: 7vmfx5ad
wandb_project_name: Cyberwheel # required if download_model is true
wandb_entity: oeschsec # required if download_model is true

experiment: EmulatorTestingIntegrationConfig
visualize: false
graph_name: EmulatorTestingIntegrationConfig
network_config: integration_config.yaml
decoy_config: decoy_hosts.yaml
host_config: host_defs_services.yaml
detector_config: detector_handler.yaml
min_decoys: 2
max_decoys: 3
reward_scaling: 10.0
reward_function: RLRedReward
num_steps: 40
num_episodes: 10
