# Evaluation Parameters
red_agent: rl_red_agent.yaml
blue_agent: inactive_blue_agent.yaml
environment: CyberwheelRL
valid_targets: servers
train_red: true
train_blue: false
campaign: false
seed: 1

checkpoint: agent
download_model: true
run: waux6tyd # required if download_model is true
wandb_project_name: Cyberwheel # required if download_model is true
wandb_entity: oeschsec # required if download_model is true

experiment: test_red_downtime
visualize: true
graph_name: test_red_downtime
network_config: 15-host-network.yaml
decoy_config: decoy_hosts.yaml
host_config: host_defs_services.yaml
detector_config: detector_handler.yaml
min_decoys: 2
max_decoys: 3
reward_scaling: 10.0
reward_function: RLReward
num_steps: 50
num_episodes: 10