# Evaluation Parameters
red_agent: brute_force_encryption_campaign.yaml
blue_agent: rl_blue_agent.yaml
environment: CyberwheelRL
valid_targets: servers
train_red: false
train_blue: true
campaign: true
seed: 1

checkpoint: agent
download_model: false
run:  # required if download_model is true
wandb_project_name:  # required if download_model is true
wandb_entity:  # required if download_model is true

experiment: RLBlueARTCampaign
visualize: true
graph_name: RLBlueARTCampaign
network_config: 15-host-network.yaml
decoy_config: decoy_hosts.yaml
host_config: host_defs_services.yaml
detector_config: detector_handler.yaml
reward_scaling: 10.0
reward_function: RLReward
num_steps: 100
num_episodes: 10