# Evaluation Parameters
red_agent: rl_red_campaign.yaml
blue_agent: dynamic_blue_agent.yaml
environment: CyberwheelEmulator
valid_targets: servers
train_red: false
train_blue: true
red_model: EmuRedRandom #Smart
blue_model: SmartEmuBlue1
campaign: true
seed: 1

checkpoint: agent
download_model: true
# run: wimxl5kg
red_run: 8d05enq4
blue_run: wimxl5kg
wandb_project_name: Cyberwheel # required if download_model is true
wandb_entity: oeschsec # required if download_model is true

experiment: MultiSubnetTest
visualize: false
graph_name: MultiSubnetTest
network_config: example_config.yaml
decoy_config: decoy_hosts.yaml
host_config: host_defs_services.yaml
detector_config: detector_handler.yaml
min_decoys: 2
max_decoys: 3
reward_scaling: 10.0
reward_function: RLRedReward
num_steps: 100
num_episodes: 10
